FROM        centos:8
RUN         mkdir /myvol
RUN         echo "hello world" > /myvol/greeting
VOLUME      /myvol




#/var/lib/docker/volumes/
#/var/lib/docker/volumes/f77b2161eb7de1bc0ffb7ebc1ccc4fd9f0c1e2ee1e7a0031ae95b7225154df30/_data